# Generated by Django 3.0.8 on 2020-08-04 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=3, unique=True)),
                ('full_name', models.CharField(max_length=25)),
                ('exchange_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Currency exchange rate cannot be less that zero')])),
            ],
        ),
    ]
