# Generated by Django 3.0.8 on 2020-08-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='exchange_rate',
            new_name='rate',
        ),
    ]
