# Generated by Django 3.1 on 2020-08-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(blank=True)),
                ('receiver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_transaction', to='accounts.account')),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_transaction', to='accounts.account')),
            ],
        ),
    ]
