# Generated by Django 3.1 on 2020-08-23 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 23, 7, 18, 49, 30735, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
